### ISSUE TITLE
Missing subtable in verbpdgm12 table view

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-input#5]
lookup for   πέφανται   
it should generate the verbpdgm12 table and display the vowel stem column (which it does) and also the stem in v column with 2 matches (which it does not). see screenshots
![Screen Shot 2020-02-19 at 3 47 05 PM](https://user-images.githubusercontent.com/41396793/74850095-d7623400-5339-11ea-9579-f4dd159e55a7.png)
![Screen Shot 2020-02-19 at 3 46 41 PM](https://user-images.githubusercontent.com/41396793/74850100-d92bf780-5339-11ea-8233-85c3ec9be804.png)

**Comment by irina060981** [comment]
@monzug , hello! Hope you are doing well in our really crazy world!

I have added subtables - missed then in previous workflow.
I have merged it and I believe it should be uploaded to the server.

**Comment by irina060981** [comment]
Merged and closed

**Comment by irina060981** [comment]
I checked it is updated here
https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/inflection-input/index.html

![image](https://user-images.githubusercontent.com/12377640/78451498-4d8fdf80-76c9-11ea-990b-4cf8f9bf9b8f.png)

**Comment by monzug** [comment]
@irina060981 Hi Irina, we are doing ok, being in lockdown since March 15. all world is going in the same direction, unfortunately. I really hope it will be over soon.... stay safe

**Comment by irina060981** [comment]
@monzug, we started to be lock down later since 30 March, and I am sure that it will be over earlier or later, would be really happy when people will be winners in this strange and difficult case.
I am really happy now that I have this job and lock down for me and my family is not so heavy!

Stay safe, Monica! And all our families and friends!

**Comment by monzug** [comment]
@irina060981 Thanks! you too. Now I can close this one...
